In [1]:
import FinanceDataReader as fdr

In [2]:
# KRX stock delisting symbol list 상장폐지 종목 전체 리스트
krx_delisting = fdr.StockListing('KRX-DELISTING')
krx_delisting

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
0,06031012,3S R,KOSDAQ,신주인수권증서,보통주,2012-05-14,2012-05-21,,NaT,NaT,,0.0,1194422.0,,
1,00684014,AK홀딩스8R,KOSPI,신주인수권증서,보통주,2014-07-28,2014-08-04,,NaT,NaT,,0.0,1278299.0,,
2,13893015,BNK금융지주 8R,KOSPI,신주인수권증서,보통주,2015-12-24,2016-01-05,,NaT,NaT,,0.0,55969410.0,,
3,13893014,BS금융지주5R,KOSPI,신주인수권증서,보통주,2014-06-18,2014-06-25,,NaT,NaT,,0.0,32791220.0,,
4,03204017,C&S자산관리 34R,KOSDAQ,신주인수권증서,보통주,2017-02-02,2017-02-09,,NaT,NaT,,0.0,3995063.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3355,034370,럭키소재,KOSPI,주권,,1979-06-23,1991-11-11,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3356,028460,태평양건설,KOSPI,주권,,1977-06-09,1991-10-05,영업활동정지 6월 계속,1991-08-28,1991-10-04,,NaN,NaN,,
3357,028450,금성투자금융,KOSPI,주권,,1986-08-29,1991-09-02,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3358,028440,삼화,KOSPI,주권,,1974-06-12,1991-07-12,감사의견 의견거절,1991-06-05,1991-07-11,,NaN,NaN,,
3359,029260,금성전기,KOSPI,주권,,1976-06-29,1991-06-13,해산 사유 발생,NaT,NaT,,NaN,NaN,,

In [6]:
krx_delisting.SecuGroup.value_counts()

주권         1720
수익증권        641
신주인수권증서     615
투자회사        173
신주인수권증권     122
선박투자회사       53
부동산투자회사      16
외국주권         11
주식예탁증권        4
Name: SecuGroup, dtype: int64

In [7]:
krx_delisting.Kind.value_counts()

보통주      2698
구형우선주     471
신형우선주     138
           48
Name: Kind, dtype: int64

In [8]:
krx_delisting[krx_delisting.SecuGroup.isin(['수익증권'])]

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
702,74701772,이지스코어부동산제117호A,KOSPI,수익증권,보통주,2017-04-14,2021-09-29,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,1000.0,32379784.0,139150,이지스자산운용
703,74702772,이지스코어부동산제117호F,KOSPI,수익증권,보통주,2017-04-14,2021-09-29,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,1000.0,550216.0,139150,이지스자산운용
706,74401722,맵스프런티어브라질1,KOSPI,수익증권,보통주,2012-05-11,2021-09-15,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,1000.0,80000000.0,036320,미래에셋자산운용
711,74702B98,이지스코어리테일302호A,KOSPI,수익증권,보통주,2019-11-20,2021-08-30,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,1000.0,51496276.0,139150,이지스자산운용
712,74701B98,이지스코어리테일302호C-I,KOSPI,수익증권,보통주,2019-11-20,2021-08-30,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,1000.0,65800000.0,139150,이지스자산운용
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2786,724011KC,한빛C6-5-1,KOSPI,수익증권,구형우선주,2000-02-22,2000-06-16,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,5000.0,5119760.0,033370,한빛투신
2830,722012J3,삼성베스트투신7,KOSPI,수익증권,구형우선주,1998-05-16,2000-03-11,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,5000.0,6020000.0,038900,삼성자산운용
2854,722012J1,삼성베스트투신6,KOSPI,수익증권,구형우선주,1998-04-02,2000-01-09,,NaT,NaT,,5000.0,10000000.0,038900,삼성자산운용
2869,722012HC,삼성베스트투신5,KOSPI,수익증권,구형우선주,1998-04-02,1999-12-28,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,5000.0,10000000.0,038900,삼성자산운용
2875,722011J7,삼성베스트주식1,KOSPI,수익증권,구형우선주,1998-12-28,1999-11-22,수익증권 신탁기간의 만료 또는 전액 중도 환수,NaT,NaT,,5000.0,2000000.0,038900,삼성자산운용

In [9]:
krx_delisting[krx_delisting.SecuGroup.isin(['투자회사'])]

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
780,099340,하나니켈1호,KOSPI,투자회사,보통주,2008-02-01,2020-07-01,존속기간 만료,NaT,NaT,기타금융,NaN,22756200.0,,
781,099350,하나니켈2호,KOSPI,투자회사,보통주,2008-02-01,2020-07-01,존속기간 만료,NaT,NaT,기타금융,NaN,3284000.0,,
1322,098150,한국아태특별,KOSPI,투자회사,보통주,2007-09-05,2012-04-23,해산 사유 발생,NaT,NaT,기타금융,NaN,7328373.0,,
1344,093820,한국유전15-1,KOSPI,투자회사,보통주,2007-01-02,2012-02-01,해산 사유 발생,NaT,NaT,기타금융,NaN,40820000.0,,
1360,094520,맵스베트남1,KOSPI,투자회사,보통주,2007-02-01,2011-11-24,신청에 의한 상장폐지,NaT,NaT,기타금융,NaN,24360821.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,034320,에머랄드 1호,KOSDAQ,투자회사,보통주,1999-04-16,2000-01-11,증권투자회사법 64조에 의한 해산사유 발생,NaT,NaT,,NaN,9595627.0,,
2870,034160,박현주 1호,KOSDAQ,투자회사,보통주,1999-04-16,1999-12-22,증권투자회사법 제64조의 규정에 의한 해산사유의 발생,NaT,NaT,,NaN,10112678.0,,
2871,034170,박현주 2호,KOSDAQ,투자회사,보통주,1999-04-16,1999-12-22,증권투자회사법 제64조의 규정에 의한 해산사유의 발생,NaT,NaT,,NaN,10078207.0,,
2872,034180,알바트로스,KOSPI,투자회사,보통주,1999-04-29,1999-12-14,존속기간 만료,NaT,NaT,,NaN,21413500.0,,
2873,034200,박현주3호,KOSPI,투자회사,보통주,1999-04-29,1999-12-10,존속기간 만료,NaT,NaT,,NaN,19957300.0,,

In [10]:
krx_delisting[krx_delisting.SecuGroup.isin(['주식예탁증권'])]

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
1034,950010,평산차업 KDR,KOSPI,주식예탁증권,보통주,2007-11-26,2015-11-05,시가총액 미달,2015-10-27,2015-11-04,서비스업,NaN,4803497.0,,
1108,950100,SBI모기지,KOSPI,주식예탁증권,보통주,2012-04-30,2015-01-07,신청에 의한 상장폐지,2014-12-24,2015-01-06,기타금융,NaN,23741000.0,,
1180,950070,중국고섬,KOSPI,주식예탁증권,보통주,2011-01-25,2013-10-04,감사의견 의견거절,2013-09-24,2013-10-02,서비스업,NaN,30000000.0,,
1364,950030,네프로아이티,KOSDAQ,주식예탁증권,보통주,2009-04-24,2011-11-05,기업의 계속성 및 경영의 투명성 등을 종합적으로 고려하여 상장폐지 기준에 해당한다고 결정,2011-10-27,2011-11-04,,NaN,6600000.0,,

In [11]:
krx_delisting[krx_delisting.Market.isin(['KOSPI', 'KOSDAQ'])]

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
0,06031012,3S R,KOSDAQ,신주인수권증서,보통주,2012-05-14,2012-05-21,,NaT,NaT,,0.0,1194422.0,,
1,00684014,AK홀딩스8R,KOSPI,신주인수권증서,보통주,2014-07-28,2014-08-04,,NaT,NaT,,0.0,1278299.0,,
2,13893015,BNK금융지주 8R,KOSPI,신주인수권증서,보통주,2015-12-24,2016-01-05,,NaT,NaT,,0.0,55969410.0,,
3,13893014,BS금융지주5R,KOSPI,신주인수권증서,보통주,2014-06-18,2014-06-25,,NaT,NaT,,0.0,32791220.0,,
4,03204017,C&S자산관리 34R,KOSDAQ,신주인수권증서,보통주,2017-02-02,2017-02-09,,NaT,NaT,,0.0,3995063.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3350,034370,럭키소재,KOSPI,주권,,1979-06-23,1991-11-11,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3351,028460,태평양건설,KOSPI,주권,,1977-06-09,1991-10-05,영업활동정지 6월 계속,1991-08-28,1991-10-04,,NaN,NaN,,
3352,028450,금성투자금융,KOSPI,주권,,1986-08-29,1991-09-02,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3353,028440,삼화,KOSPI,주권,,1974-06-12,1991-07-12,감사의견 의견거절,1991-06-05,1991-07-11,,NaN,NaN,,
3354,029260,금성전기,KOSPI,주권,,1976-06-29,1991-06-13,해산 사유 발생,NaT,NaT,,NaN,NaN,,

In [12]:
krx_delisting[krx_delisting.SecuGroup.isin(['주권'])].Kind.value_counts()

보통주      1425
신형우선주     138
구형우선주     109
           48
Name: Kind, dtype: int64

In [13]:
krx_delisting = krx_delisting[krx_delisting.SecuGroup.isin(['주권'])].reset_index(drop=True)

In [14]:
krx_delisting

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
0,001047,CJ2우B,KOSPI,주권,신형우선주,1999-01-29,2009-03-21,,NaT,NaT,서비스업,5000.0,1019041.0,,
1,001049,CJ3우B,KOSPI,주권,신형우선주,2000-01-28,2010-01-13,,NaT,NaT,서비스업,5000.0,533173.0,,
2,097957,CJ제일제당 2우B,KOSPI,주권,신형우선주,2007-09-28,2009-03-21,,NaT,NaT,음식료품,5000.0,598485.0,,
3,097959,CJ제일제당 3우B,KOSPI,주권,신형우선주,2007-09-28,2010-01-13,,NaT,NaT,음식료품,5000.0,313133.0,,
4,002105,경농(1우),KOSPI,주권,구형우선주,1995-03-21,2005-03-28,,NaT,NaT,화학,5000.0,336.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1715,034370,럭키소재,KOSPI,주권,,1979-06-23,1991-11-11,해산 사유 발생,NaT,NaT,,NaN,NaN,,
1716,028460,태평양건설,KOSPI,주권,,1977-06-09,1991-10-05,영업활동정지 6월 계속,1991-08-28,1991-10-04,,NaN,NaN,,
1717,028450,금성투자금융,KOSPI,주권,,1986-08-29,1991-09-02,해산 사유 발생,NaT,NaT,,NaN,NaN,,
1718,028440,삼화,KOSPI,주권,,1974-06-12,1991-07-12,감사의견 의견거절,1991-06-05,1991-07-11,,NaN,NaN,,
1719,029260,금성전기,KOSPI,주권,,1976-06-29,1991-06-13,해산 사유 발생,NaT,NaT,,NaN,NaN,,

In [15]:
from tqdm import tqdm
import pandas as pd

In [20]:
no_data_list = []
for ticker in tqdm(krx_delisting.Symbol):
    # KRX delisting stock data 상장폐지된 종목 가격 데이터 (상장일~상장폐지일)
    try:
        fdr.DataReader(ticker, exchange='KRX-DELISTING').to_parquet(f'data_delisted/{ticker}.parquet')
    except:
        no_data_list += [ticker]

100%|██████████| 1720/1720 [2:14:36<00:00,  4.70s/it]

In [22]:
len(no_data_list)

50

In [25]:
print(no_data_list)

['016165', '014905', '011965', '001757', '002467', '002469', '00246A', '002465', '008080', '003260', '006270', '006275', '001100', '001105', '004330', '009400', '015090', '003400', '004610', '018690', '016260', '012050', '016490', '004350', '028640', '028630', '028580', '028600', '028550', '028555', '012300', '028590', '028570', '028620', '028610', '028560', '028540', '028520', '028530', '028535', '028510', '028500', '028490', '028480', '028470', '034370', '028460', '028450', '028440', '029260']

In [23]:
from pykrx import stock

In [32]:
pd.DataFrame(no_data_list, columns=['ticker']).to_parquet('data_delisted/FDR_no_data_list.parquet')

# FinanceDataReader/krx/data.py 수정 후 추가수집

https://github.com/FinanceData/FinanceDataReader/blob/master/krx/data.py

In [5]:
import pandas as pd
tickers = pd.read_parquet('data_delisted/FDR_no_data_list.parquet').ticker

In [4]:
from tqdm import tqdm
no_data_list = []
for ticker in tqdm(tickers):
    # KRX delisting stock data 상장폐지된 종목 가격 데이터 (상장일~상장폐지일)
    try:
        fdr.DataReader(ticker, exchange='KRX-DELISTING').to_parquet(f'data_delisted/{ticker}.parquet')
    except:
        no_data_list += [ticker]

100%|██████████| 50/50 [00:28<00:00,  1.74it/s]

In [6]:
len(no_data_list)

48

In [7]:
pd.DataFrame(no_data_list, columns=['ticker']).to_parquet('data_delisted/FDR_no_data_list.parquet')

In [8]:
no_data_list[:6]

['016165', '014905', '011965', '001757', '002467', '002469']

In [9]:
import FinanceDataReader as fdr
fdr.DataReader('016165', exchange='KRX-DELISTING')

KeyError: 'Date'

In [7]:
# 2000년 이전 상장폐지 종목은 데이터가 없는듯
krx_delisting[krx_delisting.Symbol.isin(tickers)]

,Symbol,Name,Market,SecuGroup,Kind,ListingDate,DelistingDate,Reason,ArrantEnforceDate,ArrantEndDate,Industry,ParValue,ListingShares,ToSymbol,ToName
155,016165,라딕스우,KOSPI,주권,,1989-06-26,1991-04-27,,NaT,NaT,,NaN,NaN,,
228,014905,삼보컴퓨터우,KOSPI,주권,,1989-12-19,1990-09-18,,NaT,NaT,,NaN,NaN,,
251,011965,새한종금우,KOSPI,주권,,1989-10-16,1991-11-16,,NaT,NaT,,NaN,NaN,,
621,001757,한양증권2우,KOSPI,주권,,1989-10-24,1994-03-30,,NaT,NaT,,NaN,NaN,,
663,002467,화성산업2우,KOSPI,주권,,1990-02-06,1993-04-21,,NaT,NaT,,NaN,NaN,,
664,002469,화성산업3우,KOSPI,주권,,1991-05-22,1994-04-23,,NaT,NaT,,NaN,NaN,,
665,00246A,화성산업4우,KOSPI,주권,,1992-05-25,1995-04-21,,NaT,NaT,,NaN,NaN,,
666,002465,화성산업우,KOSPI,주권,,1990-01-22,1992-04-21,,NaT,NaT,,NaN,NaN,,
3320,006270,금성통신,KOSPI,주권,,1974-07-31,1995-03-23,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3321,006275,금성통신우,KOSPI,주권,,1988-07-18,1995-03-23,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3322,001100,동양정밀공업,KOSPI,주권,,1973-06-26,1994-12-23,상장폐지유예기간종료,1994-11-18,1994-12-22,,NaN,NaN,,
3323,001105,동양정밀공업우,KOSPI,주권,,1989-12-21,1994-12-23,상장폐지유예기간종료,1994-11-18,1994-12-22,,NaN,NaN,,
3324,004330,진영산업,KOSPI,주권,,1976-12-28,1994-12-23,상장폐지유예기간종료,1994-11-18,1994-12-22,,NaN,NaN,,
3325,009400,케이와이씨,KOSPI,주권,,1988-09-05,1994-12-23,상장폐지유예기간종료,1994-11-18,1994-12-22,,NaN,NaN,,
3326,015090,대미실업,KOSPI,주권,,1989-07-28,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3327,003400,삼성신약,KOSPI,주권,,1989-05-31,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3328,004610,성화,KOSPI,주권,,1989-08-25,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3329,018690,신정제지,KOSPI,주권,,1992-01-23,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3330,016260,우단,KOSPI,주권,,1989-11-11,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3331,012050,우진전기,KOSPI,주권,,1989-06-26,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3332,016490,청화상공,KOSPI,주권,,1989-01-31,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3333,004350,한일양행의약품,KOSPI,주권,,1989-08-22,1994-10-13,상장폐지유예기간종료,1994-09-03,1994-10-12,,NaN,NaN,,
3334,028640,풍진,KOSPI,주권,,1976-12-28,1994-08-16,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3335,028630,삼나스포츠,KOSPI,주권,,1989-11-15,1994-07-18,보통주 주식분포요건 미충족(최대주주등 주식수 80/100이상) 2년 계속,NaT,NaT,,NaN,NaN,,
3336,028580,경일화학공업,KOSPI,주권,,1988-01-20,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3337,028600,백산전자,KOSPI,주권,,1988-01-28,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3338,028550,서진식품,KOSPI,주권,,1989-05-30,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3339,028555,서진식품우,KOSPI,주권,,1990-05-22,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3340,012300,신한인터내쇼날,KOSPI,주권,,1989-11-08,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3341,028590,양우화학공업,KOSPI,주권,,1990-09-10,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3342,028570,우생,KOSPI,주권,,1990-09-20,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3343,028620,인성기연,KOSPI,주권,,1989-01-26,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3344,028610,중원전자,KOSPI,주권,,1988-07-28,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3345,028560,케니상사,KOSPI,주권,,1991-02-19,1994-06-13,상장폐지유예기간종료,1994-05-06,1994-06-11,,NaN,NaN,,
3346,028540,승리기계제작소,KOSPI,주권,,1991-03-07,1994-04-01,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3347,028520,영원통신,KOSPI,주권,,1991-02-09,1994-03-31,회사정리절차 폐지 결정,1994-02-23,1994-03-30,,NaN,NaN,,
3348,028530,영태전자공업,KOSPI,주권,,1988-06-18,1994-03-31,은행거래정지,1994-02-23,1994-03-30,,NaN,NaN,,
3349,028535,영태전자공업우,KOSPI,주권,,1989-10-31,1994-03-31,은행거래정지,1994-02-23,1994-03-30,,NaN,NaN,,
3350,028510,기온물산,KOSPI,주권,,1991-02-09,1993-10-16,상장폐지유예기간종료,1993-09-08,1993-10-15,,NaN,NaN,,
3351,028500,대도상사,KOSPI,주권,,1989-08-22,1993-06-24,상장폐지유예기간종료,1993-05-19,1993-06-23,,NaN,NaN,,
3352,028490,아남정밀,KOSPI,주권,,1989-09-07,1993-05-27,해산 사유 발생,1993-05-15,1993-05-26,,NaN,NaN,,
3353,028480,반도스포츠,KOSPI,주권,,1986-08-23,1992-08-19,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3354,028470,금성부품,KOSPI,주권,,1989-08-05,1992-06-17,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3355,034370,럭키소재,KOSPI,주권,,1979-06-23,1991-11-11,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3356,028460,태평양건설,KOSPI,주권,,1977-06-09,1991-10-05,영업활동정지 6월 계속,1991-08-28,1991-10-04,,NaN,NaN,,
3357,028450,금성투자금융,KOSPI,주권,,1986-08-29,1991-09-02,해산 사유 발생,NaT,NaT,,NaN,NaN,,
3358,028440,삼화,KOSPI,주권,,1974-06-12,1991-07-12,감사의견 의견거절,1991-06-05,1991-07-11,,NaN,NaN,,
3359,029260,금성전기,KOSPI,주권,,1976-06-29,1991-06-13,해산 사유 발생,NaT,NaT,,NaN,NaN,,

In [9]:
import os
files = [f for f in os.listdir('data_delisted') if len(f)==14] # 종목 데이터만 선택

In [15]:
len(files)

1622

In [16]:
pd.read_parquet(f'data_delisted/{files[0]}')

,Date,Code,Name,Market,SecuGroup,Close,UpDown,Change,ChangeRate,Open,High,Lower,Volume,Amount,MarCap
0,2009-03-19,001047,CJ2우B,KOSPI,주권,32650,0,0,0.00,0,0,0,0,0,33271688650
1,2009-03-18,001047,CJ2우B,KOSPI,주권,32650,0,0,0.00,0,0,0,0,0,33271688650
2,2009-03-17,001047,CJ2우B,KOSPI,주권,32650,0,0,0.00,0,0,0,0,0,33271688650
3,2009-03-16,001047,CJ2우B,KOSPI,주권,32650,0,0,0.00,0,0,0,0,0,33271688650
4,2009-03-13,001047,CJ2우B,KOSPI,주권,32650,0,0,0.00,0,0,0,0,0,33271688650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1999-02-04,001047,제일제당(2우B),KOSPI,주권,14600,1,1000,7.35,13600,14600,13600,17050,240588500,13882775000
2496,1999-02-03,001047,제일제당(2우B),KOSPI,주권,13600,2,-1300,-8.72,14800,15000,13600,26780,397083000,12931900000
2497,1999-02-02,001047,제일제당(2우B),KOSPI,주권,14900,1,100,0.68,14800,15000,14800,28480,424696000,14168037500
2498,1999-02-01,001047,제일제당(2우B),KOSPI,주권,14800,2,-200,-1.33,14000,15100,13500,27720,406817000,14072950000
2499,1999-01-29,001047,제일제당(2우B),KOSPI,주권,15000,1,1400,10.29,13600,15300,12000,47560,688146000,14263125000

In [17]:
data = pd.concat([pd.read_parquet(f'data_delisted/{file}') for file in files], axis=0)

In [19]:
data.to_parquet('krx_delisted.parquet')